### ISSUE TITLE
PHP 7.0 Error

### ISSUE THREAD

**Issue by jwatkins0101** [jayelkaake/enhancedgrid#53] opened 2016-10-26 14:06 UTC
Need help with this error.
error:  Uncaught TypeError: Argument 1 passed to TBT_Enhancedgrid_Model_Collection_Decorator_Abstract::setCollection() must be an instance of TBT_Enhancedgrid_Model_Resource_Eav_Mysql4_Product_Collection, instance of Mage_CatalogSearch_Model_Resource_Search_Collection given, called in /mnt/bluedata/home/magneto/public_html/app/code/community/TBT/Enhancedgrid/Model/Product/Collection/Category/Decorator.php on line 30 and defined in /mnt/bluedata/home/magneto/public_html/app/code/community/TBT/Enhancedgrid/Model/Collection/Decorator/Abstract.php:30

**Comment by jayelkaake** [comment] 2017-02-08 18:47
Hmmm will look at this - thanks for the tip!

**Comment by jayelkaake** [comment] 2017-02-08 18:50
Although personally I really don't recommend using Magento on PHP 7.0. I've had a ton of problems trying to get it to work in the past on PHP 7 (tried again a month ago and spent all day fixing random issues).

**Comment by Blackskyliner** [comment] 2017-05-05 14:03
The error itself does not sound like it's PHP7.0 related? So the issue should be renamed I guess?

EDIT: Oh and there seems to be a module providing PHP7.0 support for Magento, at least for pristine installations https://github.com/Inchoo/Inchoo_PHP7

**Comment by jayelkaake** [comment] 2017-05-05 14:12
Your issue is that the rewrite of that class is not working. Find the module that is conflicting and fix it, then you should be good.

**Comment by techzotezo** [comment] 2018-01-03 05:04
Hi,
We are using PHP7.0 with magento 1.9.3.3 but I am facing one issue that after filtering through manufacturer result is not showing properly.It is showing only when after refreshing or after clicking ctrl+f5

Why the issue is happening? Please provide me a solution.

Thanks

**Comment by jayelkaake** [comment] 2018-01-03 05:04
What's appearing in the logs?

**Comment by techzotezo** [comment] 2018-01-03 05:40
Nothing showing in error log but anyway filter is only working only when we click ctrl+f5.First time filter results not showing.
2018-01-03T04:54:06+00:00 ERR (3): Warning: simplexml_load_string(): &lt;!-----   in www/lib/Varien/Simplexml/Config.php on line 510
2018-01-03T04:54:06+00:00 ERR (3): Warning: simplexml_load_string():     ^  in www/lib/Varien/Simplexml/Config.php on line 510
2018-01-03T04:54:07+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): Entity: line 6: parser error : Opening and ending tag mismatch: hr line 5 and body  in www/app/code/local/Mgt/Base/Model/Feed.php on line 77
2018-01-03T04:54:07+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): &lt;/body&gt;  in www/app/code/local/Mgt/Base/Model/Feed.php on line 77
2018-01-03T04:54:07+00:00 ERR (3): Warning: SimpleXMLElement::__construct():        ^  in www/app/code/local/Mgt/Base/Model/Feed.php on line 77
2018-01-03T04:54:07+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): Entity: line 7: parser error : Opening and ending tag mismatch: body line 3 and html  in www/app/code/local/Mgt/Base/Model/Feed.php on line 77
2018-01-03T04:54:07+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): &lt;/html&gt;  in www/app/code/local/Mgt/Base/Model/Feed.php on line 77
2018-01-03T04:54:07+00:00 ERR (3): Warning: SimpleXMLElement::__construct():        ^  in /app/code/local/Mgt/Base/Model/Feed.php on line 77
2018-01-03T04:54:07+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): Entity: line 8: parser error : Premature end of data in tag html line 1  in /app/code/local/Mgt/Base/Model/Feed.php on line 77
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): Entity: line 1: parser error : Space required after the Public Identifier  in /app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;  in /app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct():                                                  ^  in /app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): Entity: line 1: parser error : SystemLiteral &quot; or ' expected  in app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;  in /home/zotezodevphp1/www/app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct():                                                  ^  in /home/zotezodevphp1/www/app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): Entity: line 1: parser error : SYSTEM or PUBLIC, the URI is missing  in /app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;  in app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct():                                                  ^  in app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): Entity: line 9: parser error : Opening and ending tag mismatch: hr line 7 and body  in /home/zotezodevphp1/www/app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): &lt;/body&gt;&lt;/html&gt;  in app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct():        ^  in app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): Entity: line 9: parser error : Opening and ending tag mismatch: body line 4 and html  in app/code/core/Mage/AdminNotification/Model/Feed.php on line 173
2018-01-03T04:54:11+00:00 ERR (3): Warning: SimpleXMLElement::__construct(): Entity: line 9: parser error : Premature end of data in tag html line 2  in /app/code/core/Mage/AdminNotification/Model/Feed.php on line 173

**Comment by techzotezo** [comment] 2018-01-03 05:53
What is the issue? I want to make it live today ASAP but due to this error we cannot able to launch it.Please kindly help me in this concern so that I can make it live it by today...

**Comment by jayelkaake** [comment] 2018-01-03 16:07
Those errors are totally unrelated, but you should fix them anyways. You're not seeing the real error because you have so many errors from other things most likely. Fix your errors and make sure PHP error reporting is working and look in the server logs to figure out what's happening.

Since this is a free and open source extension we rely on the community members like yourself to figure out your own issues and post the solutions here to help others. Since this isn't an issue being experienced by many people, and to my knowledge and testing PHP 7 is working with the module, there's likely an issue with your own install specifically. Usually this is a module conflict - rewrites or something related to that instead. 

I recommend that you need to clean up your logs so you can see errors properly and then use some tutorials around the web to investigate and fix any module conflicts in your install. That should help you find the issue. Good luck!

**Comment by techzotezo** [comment] 2018-01-04 08:26
After clearing the cache now showing this error-
 
Fatal error: Uncaught TypeError: Argument 1 passed to TBT_Enhancedgrid_Model_Product_Collection_Category_Decorator::setCollection() must be an instance of TBT_Enhancedgrid_Model_Resource_Eav_Mysql4_Product_Collection, instance of Mage_Catalog_Model_Resource_Product_Collection given, called in var/ait_rewrite/Mage_Adminhtml_Block_Catalog_Product_Grid.php on line 890 and defined in app/code/community/TBT/Enhancedgrid/Model/Product/Collection/Category/Decorator.php:29 Stack trace: #0 
var/ait_rewrite/Mage_Adminhtml_Block_Catalog_Product_Grid.php(890): TBT_Enhancedgrid_Model_Product_Collection_Category_Decorator->setCollection(Object(Mage_Catalog_Model_Resource_Product_Collection)) #1 app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(522): TBT_Enhancedgrid_Block_Catalog_Product_Grid->_preparePage() #2 app/code/local/Mage/Adminhtml/Block/Catalog/Product/Grid.php(135): Mage_Adminhtml_Block_Widget_Grid->_prepar in app/code/community/TBT/Enhancedgrid/Model/Product/Collection/Category/Decorator.php on line 29

**Comment by jayelkaake** [comment] 2018-01-04 15:30
So that's, as suspected, because of an extension rewrite conflict. 💁‍♂️  You have another extension installed that is overwriting the `TBT_Enhancedgrid_Model_Resource_Eav_Mysql4_Product_Collection` class.

Use an extension conflict tool to figure out what module is doing it, or see what class is actually being passed into the `setCollection` method (using `get_class()`) and that should help you solve the conflict.

I'm going to close this because I can confirm that this is not an issue with the software and rather a conflict with other extensions installed specific to you (and the person above's) store.

**Closed by jayelkaake** 2018-01-04 15:30 UTC
