### ISSUE TITLE
Duplicate category names in "categories"

### ISSUE THREAD

**Issue by nesh-younify** [jayelkaake/enhancedgrid#9] opened 2015-01-23 13:56 UTC
When displaying `categories` on product list I can see duplicate category names. I managed to trace problem to the join in `TBT_Enhancedgrid_Model_Product_Collection_Category_Decorator::addCategories`
```php
 $collection->joinField( 'categories', $ccev_t, "GROUP_CONCAT({$alias_prefix}categories.value)", 'entity_id=category_id',
    "{$alias_prefix}categories.attribute_id={$category_name_attribute_id}", 'left' );
```
Any ideas how to fix it?

Example:

Product is in category `cat/dog`, but list display `cat, cat, cat, cat, dog` (1st category gets displayed multiple times).

**Comment by triplexita** [comment] 2015-12-17 10:22
Yes i have the some problem in my magneto .... redoundand duplicated category in gategory grid filed .... i think that i have problems in my category table of magento, but i checked db table and all is fine ...this is bug of this module! how can i resolve this?

**Comment by pquerner** [comment] 2016-02-16 15:26
Output SQL Query

```
SELECT `e`.*, `at_qty`.`qty`, `at_category_id`.`category_id`, GROUP_CONCAT(at_categories.value) AS `categories`, `at_category`.`value` AS `category` FROM `catalog_product_entity` AS `e`
 LEFT JOIN `cataloginventory_stock_item` AS `at_qty` ON (at_qty.`product_id`=e.entity_id) AND (at_qty.stock_id=1)
 LEFT JOIN `catalog_category_product` AS `at_category_id` ON (at_category_id.`product_id`=e.entity_id)
 LEFT JOIN `catalog_category_entity_varchar` AS `at_categories` ON (at_categories.`entity_id`=at_category_id.category_id) AND (at_categories.attribute_id=41)
 LEFT JOIN `catalog_category_entity_varchar` AS `at_category` ON (at_category.`entity_id`=at_category_id.category_id) AND (at_category.attribute_id=41) GROUP BY `e`.`entity_id`
```

The problem is the "GROUP_CONCAT"

I'm testing it right now.

**Comment by pquerner** [comment] 2016-02-16 15:32
Got it. You have to add a "DISTINCT" to the GROUP_CONCAT. WIll do a PR shortly.

**Comment by triplexita** [comment] 2016-02-16 17:01
hi, where i must insert this code? in wich file ? in wich folder?
Il giorno 16/feb/2016 16.33, "Pascal Querner" <notifications@github.com> ha
scritto:

**Comment by pquerner** [comment] 2016-02-16 18:12
@triplexita You can either use my fork of this module in the meantime, or check out the commit for yourself. In the commit itself you see the changed line and file specificly.

**Comment by triplexita** [comment] 2016-02-16 19:56
hi where can i find this ???
Il giorno 16/feb/2016 19.12, "Pascal Querner" <notifications@github.com> ha
scritto:

**Comment by pquerner** [comment] 2016-02-16 19:58
Here you can find the commit: https://github.com/MSCG/enhancedgrid/commit/965c7fb26b049e48085509a6264b2e218c942366
Here you can find my fork: https://github.com/MSCG/enhancedgrid

**Comment by triplexita** [comment] 2016-02-16 21:28
hohohoho very very good, i changhed line in thi file with your code and all
work fine and fixed now. Thank you!

2016-02-16 20:58 GMT+01:00 Pascal Querner <notifications@github.com>:

**Closed** 2016-02-17 05:39 UTC

**Comment by triplexita** [comment] 2016-02-17 06:45
hi there are very good idea extend this module for work also in upsel
crossell and related tab in product editing ..... in this tab not is semple
filter products with normal grid
Il giorno 17/feb/2016 06.39, "Jay El-Kaake" <notifications@github.com> ha
scritto:
